name: scrna-mini
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - r-base=4.3.3
  - r-seurat=5.0.3
  - r-tidyverse=2.0.0
  - r-patchwork=1.2.0
  - r-knitr=1.48
  - r-rmarkdown=2.29
  - r-yaml=2.3.10
  - r-SeuratObject=5.0.2
  - r-Matrix=1.6_5
  - r-ggplot2=3.5.1
  - r-ggraph=2.2.1
  - r-igraph=2.0.3
  - r-readr=2.1.5
  - r-devtools=2.4.5
  - pandoc=3.1.12.3
  - mamba
  - make
  - git
  - seqtk=1.4
  - minimap2=2.28
  - bedtools=2.31.1
  - samtools=1.20
  - pyyaml=6.0.2
  - pip

# Note: Cell Ranger 7.2.0 must be installed separately from 10x Genomics and added to PATH.

